---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.doris.io
  resources:
  - bes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.doris.io
  resources:
  - bes/finalizers
  verbs:
  - update
- apiGroups:
  - operator.doris.io
  resources:
  - bes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.doris.io
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.doris.io
  resources:
  - brokers/finalizers
  verbs:
  - update
- apiGroups:
  - operator.doris.io
  resources:
  - brokers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.doris.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.doris.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - operator.doris.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.doris.io
  resources:
  - ves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.doris.io
  resources:
  - ves/finalizers
  verbs:
  - update
- apiGroups:
  - operator.doris.io
  resources:
  - ves/status
  verbs:
  - get
  - patch
  - update
