apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: calico-conf
  namespace: kube-system
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "type": "calico",
    "datastore_type": "kubernetes",
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
        "type": "k8s"
    },
    "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
    }   
  }'
